permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Trend-E"
  description:
    A local e-commerce website focused on selling trendy eyewear and lens repair services.
  font_url: "https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,400i,600,700,800"
