permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "Trend-E"
  description:
    A local e-commerce website focused on selling trendy eyewear and lens repair services.
  font_url: "https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,400i,600,700,800"
  colors:
    accent: "--color-primary-dark"
    patterns:
      brand.logos: "--color-secondary"
      icons.icons: "--color-primary"
  layouts:
    default:
      The default layout should be used for almost every page, it includes the website's primary header and footer.
    product:
      This layout is to be used on the products known as the eye glasses page on the site.

  rationales:
    typefaces.primary:
      Nunito Sans was selected to to it's classic and clean look. The san-serif font gives the site a modern feeling which is appropriate as the overall tone for an e-commerce site concerned with fashion and aesthetics. It is also very readable at all sizes and provides excellent accessibility.
    colors.primary:
      The primary color is a dark colour representing an edgy and classic feel. It is neutral and gives the site a sophisticated and timeless feeling. This color should be used as text on lighter backgrounds, body text, backgrounds for cards, banner and footer.
    colors.secondary:
      This colour is a fun and bright colour used within the brand logo. This color should be used on the navigation background, card backgrounds and buttons colours.
    colors.accent:
      This colour is a muted gold color representing fashion and used to add a contemporary flare. This color should be used for card backgrounds.
    colors.neutral:
      This colour is a beige colour which represents softness and femininity. This color should be for card backgrounds.

collections:
  products:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
