title: "Buttons"
description:
  Buttons should be used in situations where a dramatic, obvious action is required. Try not to over use buttons because they should be the primary call-to-action for a screen.

patterns:
  basic:
    title: "Basic"
    description:
      Default to using the basic button it should always be used in front of a light backgrounds.
    width: "12em"
    fields:
    - name: text
      type: string
      example: "Buy Now"
    - name: url
      type: url
      example: "/products/"

  ghost:
    title: "Ghost"
    description:
      The ghost button is specificially for banners where it will be placed in front of a busy image.
    background: "--color-primary-light"
    fields:
    - name: text
      type: string
      example: "View collection"
    - name: url
      type: url
      example: "/products/"
