title: "Sections"
description:
  Banner are used to showcase information used for advertising purposes. The purpose of a banner is to promote the brand or product in order to generate online vistors and increase sales.

patterns:
  plain-bullet:
    fields:
      - name: heading
        type: string
        example: "Information Collection and Use"
      - name: text
        type: string
        example: "We collect several different types of information for various purposes to provide and improve our Service to you."
  basic-information:
    fields:
      - name: heading
        type: string
        example: "Information Collection and Use"
      - name: text-1
        type: string
        example: "Text String 1."
      - name: text-2
        type: string
        example: "Text String 2."
      - name: text-3
        type: string
        example: "Text String 3."
      - name: text-4
        type: string
        example: "Text String 4."
  secondary-information:
    fields:
      - name: heading
        type: string
        example: "Definitions"
      - name: heading-1
        type: string
        example: "Subheader-1"
      - name: text-1
        type: string
        example: "Text String 1."
      - name: heading-2
        type: string
        example: "Subheader-2"
      - name: text-2
        type: string
        example: "Text String 2."
      - name: heading-3
        type: string
        example: "Subheader-3"
      - name: text-3
        type: string
        example: "Text String 3."
      - name: heading-4
        type: string
        example: "Subheader-4"
      - name: text-4
        type: string
        example: "Text String 4."

  company-section:
      fields:
        - name: heading
          type: string
          example: "Who are we"
        - name: text
          type: string
          example: "A new company to the eyewear scene, here at Trend-E, we believe everyone should have access to high-quality, affordable eyewear. We want our eyeglass wearing friends to feel beautiful and to find the perfect pair of frames that complement their own unique personality. Our company offers free shipping and reliable service everytime helping to transform the hassle of buying eyewear into a fun and stress-free experience."
