title: "Cards"
description:
  Cards are used to separate information in a logical way. They should be used to contain content and images pertaining to a single action or subject.

patterns:
  product:
    title: "Product Card"
    description:
      This card is used to showcase product and should be on a page which features product.
    feilds:
    - name: date
      type: object
      date:
        source: "site.products[0]"
        type: Product
    width: "12em"
  illustration-card-shop:
    title: "Illustration Card: Shop"
    description:
      This card is used as a call to action highlighting illustrations found in a smaller grid.
  illustration-card-fab:
    title: "Illustration Card: Fab"
    description:
      This card is used as a call to action highlighting illustrations found in a smaller grid.
  illustration-card-oldies:
    title: "Illustration Card: Oldies"
    description:
      This card is used as a call to action highlighting illustrations found in a smaller grid.
  product-detail:
    title: "Product Card"
    description:
      This card is used showcase a product.
  information-card:
    title: "Information Card"
    description:
      This card is used provide further information on a product.
