title: "Banners"
description:
  Banner are used to showcase information used for advertising purposes. The purpose of a banner is to promote the brand or product in order to generate online vistors and increase sales.

patterns:
  banner-card:
    title: "Main Banner"
    description:
      This banner is used throughout the site as the main banner. Call to actions are changed depending on which page the banner is on.
    fields:
      - name: heading
        type: string
        example: "New Year ｜ New You"
      - name: text
        type: string
        example: "See the best of best of 2019"
      - name: icon
        type: string
        example: "#banner-1"
      - name: button_text
        type: string
        example: "View Collection"
      - name: button_url
        type: url
        example: "/banner-1/"
  banner-light:
    title: "Light Responsive Banner"
    description:
      Informative banner to highlight the benefits of dual lens, this is found on the checkout page of the site.
  banner-lens:
    title: "High Quality Lens Banner"
    description:
      Informative banner to highlight the high quality lens, this is found on the homepage of the site.
